// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxikD9o432UHZiw2wdaWh7V27bGgTmRnc',
    appId: '1:352933754129:web:a503550034e888ec1f88b0',
    messagingSenderId: '352933754129',
    projectId: 'moodtrack-72ea8',
    authDomain: 'moodtrack-72ea8.firebaseapp.com',
    storageBucket: 'moodtrack-72ea8.appspot.com',
    measurementId: 'G-W9QQ7CHT3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qNYLfrhpZO3QFPIimPWgZIiFldPFZYU',
    appId: '1:352933754129:android:b2d5e7036123531d1f88b0',
    messagingSenderId: '352933754129',
    projectId: 'moodtrack-72ea8',
    storageBucket: 'moodtrack-72ea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsRalg-gq3g92EVxA8QIdR5lJ7E3Jlto',
    appId: '1:352933754129:ios:fa78d7bc1f6696111f88b0',
    messagingSenderId: '352933754129',
    projectId: 'moodtrack-72ea8',
    storageBucket: 'moodtrack-72ea8.appspot.com',
    iosBundleId: 'com.example.moodtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsRalg-gq3g92EVxA8QIdR5lJ7E3Jlto',
    appId: '1:352933754129:ios:0b88a6758497ad261f88b0',
    messagingSenderId: '352933754129',
    projectId: 'moodtrack-72ea8',
    storageBucket: 'moodtrack-72ea8.appspot.com',
    iosBundleId: 'com.example.moodtracker.RunnerTests',
  );
}
